package reverseengineer

import (
	"fmt"
	"strings"
)

// readOnlyStorageIntegrationProperties are properties returned by
// DESC STORAGE INTEGRATION that are generated by Snowflake and must
// not appear in a CREATE STORAGE INTEGRATION statement.
var readOnlyStorageIntegrationProperties = map[string]bool{
	"STORAGE_AWS_IAM_USER_ARN":    true,
	"STORAGE_AWS_EXTERNAL_ID":     true,
	"AZURE_CONSENT_URL":           true,
	"AZURE_MULTI_TENANT_APP_NAME": true,
	"STORAGE_GCP_SERVICE_ACCOUNT": true,
}

// BuildStorageIntegrationDDL: Given DESC STORAGE INTEGRATION rows, when DDL
// reconstruction runs, then a CREATE STORAGE INTEGRATION statement is produced.
//
// Each row is expected to have PROPERTY and PROPERTY_VALUE columns (uppercased,
// as produced by the Snowflake repository's scanRows). Read-only properties that
// are generated by Snowflake are silently excluded from the output.
//
// Returns (ddl, true) on success, or ("", false) when the DESC rows do not
// contain the minimum required properties (STORAGE_PROVIDER).
func BuildStorageIntegrationDDL(name string, descRows []Row) (string, bool) {
	if len(descRows) == 0 {
		return "", false
	}

	props := descRowsToMap(descRows)

	// STORAGE_PROVIDER determines which provider-specific properties are valid.
	provider, ok := props["STORAGE_PROVIDER"]
	if !ok || strings.TrimSpace(provider) == "" {
		return "", false
	}
	upperProvider := strings.ToUpper(strings.TrimSpace(provider))

	enabled := "TRUE"
	if ev := strings.ToUpper(strings.TrimSpace(props["ENABLED"])); ev == "FALSE" {
		enabled = "FALSE"
	}

	var b strings.Builder
	fmt.Fprintf(&b, "CREATE STORAGE INTEGRATION IF NOT EXISTS %s\n", quoteIdentifier(name))
	fmt.Fprintf(&b, "  TYPE = EXTERNAL_STAGE\n")
	fmt.Fprintf(&b, "  STORAGE_PROVIDER = %s\n", quoteLiteral(upperProvider))
	fmt.Fprintf(&b, "  ENABLED = %s", enabled)

	// Provider-specific parameters.
	switch upperProvider {
	case "S3", "S3GOV", "S3CHINA":
		if arn := props["STORAGE_AWS_ROLE_ARN"]; strings.TrimSpace(arn) != "" {
			fmt.Fprintf(&b, "\n  STORAGE_AWS_ROLE_ARN = %s", quoteLiteral(arn))
		}
		if acl := props["STORAGE_AWS_OBJECT_ACL"]; strings.TrimSpace(acl) != "" {
			fmt.Fprintf(&b, "\n  STORAGE_AWS_OBJECT_ACL = %s", quoteLiteral(acl))
		}
	case "AZURE":
		if tenantID := props["AZURE_TENANT_ID"]; strings.TrimSpace(tenantID) != "" {
			fmt.Fprintf(&b, "\n  AZURE_TENANT_ID = %s", quoteLiteral(tenantID))
		}
	}

	// STORAGE_ALLOWED_LOCATIONS is required; default to '*' when absent.
	if allowedLocs := props["STORAGE_ALLOWED_LOCATIONS"]; strings.TrimSpace(allowedLocs) != "" {
		fmt.Fprintf(&b, "\n  STORAGE_ALLOWED_LOCATIONS = (%s)", storageLocationsToTuple(allowedLocs))
	} else {
		fmt.Fprintf(&b, "\n  STORAGE_ALLOWED_LOCATIONS = ('*')")
	}

	// STORAGE_BLOCKED_LOCATIONS is optional.
	if blockedLocs := props["STORAGE_BLOCKED_LOCATIONS"]; strings.TrimSpace(blockedLocs) != "" {
		fmt.Fprintf(&b, "\n  STORAGE_BLOCKED_LOCATIONS = (%s)", storageLocationsToTuple(blockedLocs))
	}

	// COMMENT is optional.
	if comment := props["COMMENT"]; strings.TrimSpace(comment) != "" {
		fmt.Fprintf(&b, "\n  COMMENT = %s", quoteLiteral(comment))
	}

	return b.String(), true
}

// descRowsToMap: Given DESC rows, when normalization runs, then uppercase
// PROPERTY keys are mapped to values while unsupported/read-only rows are skipped.
func descRowsToMap(rows []Row) map[string]string {
	props := make(map[string]string, len(rows))
	for _, row := range rows {
		prop, ok := getString(row, "PROPERTY")
		if !ok {
			continue
		}
		key := strings.ToUpper(strings.TrimSpace(prop))
		if readOnlyStorageIntegrationProperties[key] {
			continue
		}
		// Empty property_value is stored as "" (getString returns "" + false).
		val, _ := getString(row, "PROPERTY_VALUE")
		props[key] = val
	}
	return props
}

// storageLocationsToTuple: Given comma-separated locations, when conversion
// runs, then a safely quoted SQL tuple string is returned.
//
// Example: "s3://bucket/path/,s3://other/path/" → "'s3://bucket/path/', 's3://other/path/'"
func storageLocationsToTuple(locations string) string {
	parts := strings.Split(locations, ",")
	quoted := make([]string, 0, len(parts))
	for _, part := range parts {
		trimmed := strings.TrimSpace(part)
		if trimmed != "" {
			quoted = append(quoted, quoteLiteral(trimmed))
		}
	}
	return strings.Join(quoted, ", ")
}
